# version: '3'  ---obsolete
services:
   app:
        image: devops-for-programmers-project-74
        build:
              context: .
              dockerfile: Dockerfile
        command: make dev   
        ports:
             - "8080:8080"
        volumes:
             - "./app:/app/"
